wvcsc_vehicle_interface:
  ros__parameters:
    max_speed: 1.0
    max_steering_angle: 0.6109
    command_timeout_sec: 0.5
    publish_twist_cmd: true
    twist_cmd_topic: /twist_cmd
    cmd_vel_topic: /cmd_vel
